config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings    
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.urls import path
from .views import ArticleList, InfoList, ArticleDetailView, ArticleSList

app_name = "mysite"

urlpatterns = [
	path("", ArticleList.as_view(), name="Article"),
	path("Article/", ArticleSList.as_view(), name="ArticleS"),
	path("detail/<slug:slug>/",ArticleDetailView.as_view(), name="detail"),
	path("rezomie/", InfoList.as_view(), name="infos"),
]

mysite/models.py
from django.db import models


class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100, unique=True, null=True)
	description = models.TextField()
	status = models.BooleanField(default=False)
	time = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.title

class info(models.Model):
	name = models.CharField(max_length=100)
	pic = models.ImageField(upload_to="media/")
	slug = models.SlugField(max_length=100, unique=True, null=True)
	description = models.TextField()
	skils = models.CharField(max_length=100, blank=True)
	skils1 = models.CharField(max_length=100, blank=True)
	skils2 = models.CharField(max_length=100, blank=True)
	skils3 = models.CharField(max_length=100, blank=True)
	skils4 = models.CharField(max_length=100, blank=True)
	skils5 = models.CharField(max_length=100, blank=True)
	skils6 = models.CharField(max_length=100, blank=True)
	skils7 = models.CharField(max_length=100, blank=True)
	skils8 = models.CharField(max_length=100, blank=True)
	skils9 = models.CharField(max_length=100, blank=True)
	skils10 = models.CharField(max_length=100, blank=True)
	skils11 = models.CharField(max_length=100, blank=True)
	skils12 = models.CharField(max_length=100, blank=True)

	def __str__(self):
		return self.name

mysite/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, info
from django.views.generic import ListView, DetailView

class ArticleList(ListView):
	queryset = Article.objects.all().order_by("-time")[0:4]
	template_name = "article/article.html"

class ArticleSList(ListView):
	queryset = Article.objects.filter(status=True).order_by("-time")
	template_name = "article/articles.html"
	paginate_by = 4

class ArticleDetailView(DetailView):
	template_name = "article/articledetail.html"

	def get_queryset(self):
		global articles
		slug = self.kwargs.get("slug")
		articles = get_object_or_404(Article, slug=slug)
		return Article.objects.filter(slug=slug)

	def get_context_data(self, **kwargs):
		context =  super().get_context_data(**kwargs)
		context["articles"] = articles
		return context

class InfoList(ListView):
	model = info
	template_name = "article/info.html"

templates/article/article.html
{% extends "base.html" %}
{% block header %}
<div class="container">
	<div class="row align-items-center">
		<div class="col-md-6">
			<h2 class="display-4 mb-4 mt-4">بازدید از <span class="text-primary">روزمه</span> من در این سایت</h2>
			<p class="lead text-muted mb-4">من در لینک پایین رزومه خود را برای نمایش گذاشتم که میتوانید با کلیک روی ان رزومه من را مشاهده کنید.</p>
			<div class="text-center text-md-end">
			<a href="{% url 'mysite:infos' %}" class="btn btn-primary">بازید رزومه</a>
		</div>
		</div>
		<div class="col-md-6">
			<img class="img-fluid" src="media/media/2.png">
		</div>
	</div>
</div>
<div class="bg-white p-5">
<div class="container">
	<h2 class="mb-4 text-center">ویژگی های سایت</h2>
	<div class="row">
		<div class="col-lg-4 col-md 6">
			<div class="card text-center text-black bg-light mb-3 p-4">
				<div class="card-body">
					<div class="mb-3">
						<a href="{% url 'mysite:ArticleS' %}"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-file-text" viewBox="0 0 16 16">
							<path d="M5 4a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm-.5 2.5A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zM5 8a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1H5z"/>
							<path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
						  </svg></a>
						</div>
				  <h5 class="card-title">مقالات</h5>
				  <p class="card-text text-muted">در سایت ما قسمتی وجود دارد که میتوانید مقالات را در آن ببینید </p>
				</div>
			  </div>
		</div>
		<div class="col-lg-4 col-md 6">
			<div class="card text-center text-black bg-light mb-3 p-4">
				<div class="card-body">
					<div class="mb-3">
					<a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-film" viewBox="0 0 16 16">
						<path d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0v6h8V1H4zm8 8H4v6h8V9zM1 1v2h2V1H1zm2 3H1v2h2V4zM1 7v2h2V7H1zm2 3H1v2h2v-2zm-2 3v2h2v-2H1zM15 1h-2v2h2V1zm-2 3v2h2V4h-2zm2 3h-2v2h2V7zm-2 3v2h2v-2h-2zm2 3h-2v2h2v-2z"/>
					  </svg></a>
					</div>
				  <h5 class="card-title">اموزشات</h5>
				  <p class="card-text text-muted">در سایت ما قسمتی وجود دارد که فیلم های آموزشی خود را در آن جا میزاریم</p>
				</div>
			  </div>
		</div>
		<div class="col-lg-4 col-md 6">
			<div class="card text-center text-black bg-light mb-3 p-4">
				<div class="card-body">
					<div class="mb-3">
						<a href="{% url 'mysite:infos' %}"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
							<path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
							<path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
						  </svg></a>
					</div>
				  <h5 class="card-title">رزومه</h5>
				  <p class="card-text text-muted">در سایت ما قسمتی وجود دارد که رزومه و سرگذشت خود را در آن قرار دادم</p>
				</div>
			  </div>
		</div>
	</div>
</div>
</div>

{% endblock %}
{% block content %}

<div class="py-4">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-md-6">
				<h2 class="display-4">
					بازدید از صفحه <span class="text-warning">مقالات</span>
					<p class="lead text-muted mb- mt-3">
						برای بازدید از تمامی مقالات سایت به روی دکمه زیر بزنید
					</p>
					<div class="text-center text-md-end">
						<a href="{% url 'mysite:ArticleS' %}" class="btn btn-warning">صفحه مقالات</a>
					</div>
				</h2>
			</div>
			<div class="col-md-6">
				<img class="img-fluid" src="media/media/3.png">
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/article/articledetail.html
{% extends "base.html" %}


{% block content %}
<div class="container">
	<br>
	<div class="row">
		<div class="col-12">
			<h3 class="p-3">
				{{articles.title}}
			</h3>
			<p class="text-muted">
				{{articles.description}}	
			</p>
			<p class="text-muted">
				{{articles.time}}	
			</p>
		</div>
	</div>
</div>
{% endblock %}
{% block up-header %}
<div class="py-4">
	<div class="container">
		<h2 class="display-4 text-center text-warning">پایان مقاله</h2>
		<hr>
		<div class="row align-items-center">
			<div class="col-md-6">
				<h2 class="display-4">
					بازدید از صفحه <span class="text-warning">مقالات</span>
					<p class="lead text-muted mb- mt-3">
						برای بازدید از تمامی مقالات سایت به روی دکمه زیر بزنید
					</p>
					<div class="text-center text-md-end">
						<a href="{% url 'mysite:infos' %}" class="btn btn-warning">صفحه مقالات</a>
					</div>
				</h2>
			</div>
			<div class="col-md-6">
				<img class="img-fluid" src="/media/media/3.png">
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/article/articles.html
{% extends "base.html" %}
{% block logo %}
{% endblock %}
{% block content %}
<div class="container">
<h2 class="p-3 mt-3 display-4">پست های سایت</h2>
</div>
<div class="container">
	<div class="row">
{% for a in object_list %}
		<div class="col-lg-12 col-md-6 p-4">
	<a href="{% url 'mysite:detail' a.slug %}"><h3>{{a.title}}</h3></a>
	<p class="text-muted">{{a.description|truncatewords:30}}</p>
	<p class="text-muted">{{a.time}}</p>
	<a href="{% url 'mysite:detail' a.slug %}" class="btn btn-primary" role="button">ادامه</a>
</div>
{% endfor %}
</div>
<div class="d-flex justify-content-center p-3">
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-danger" style="width: 80px;">قبلی</a>
        {% endif %}

        <span class="current">
            صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class=""></a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-success" style="width:80px;">بعدی &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</div>
{% endblock %}

templates/article/deleted.html
<div class="container">
	<div class="row p-2">
		<div class="col-sm-12 col-md-4 col-lg-4 mt-4 align-items-start rounded-3 bg-white shadow-lg">
			<h4 class="p-2 text-center">درباره سایت</h4>
			<hr>
			<p class="text-muted text-center mt-4 ">
				من جواد حسین زاده در این سایت میخاهم هم یک اینترویوی از خود بزارم و هم دانش و دانسته های خود را با شما ها به اشتراک بزارم
			</p>

		</div>
		<div class="col-sm-12 col-md-7 col-lg-7 mt-4 bg-white mx-lg-4 mx-md-4 rounded-3 shadow-lg">
			<h4 class="p-2 text-center">راه های ارتباطی</h4>
			<hr>
			<p class="text-muted">شماره همراه : 09105675936</p>
			<p class="text-muted">ایمیل : javadhoseinzde80@gmail.com</p>
			<p class="text-muted">اینستاگرام : j.cloud</p>

		</div>
	</div>
</div>



<div class="bg-white">
    <div class="container">
    <br><h4 class="mx-4">پست های اخیر</h4><hr>
    </div>
    <div class="container">
        <div class="row">
    {% for a in object_list %}
            <div class="col-lg-12 col-md-6 p-4">
        <h3>{{a.title}}</h3>
        <p class="text-muted">{{a.description|truncatewords:30}}</p>
        <p class="text-muted">{{a.time}}</p>
        <a href="{% url 'mysite:detail' a.slug %}" class="btn btn-dark" role="button">ادامه</a>
    </div>
    <hr>
    {% endfor %}
    </div>
    </div>
    </div>

templates/article/info.html
{% extends "base.html" %}
{% block logo %}

{% endblock %}
{% block content %}
<br>
<div class="container-lg">
	<div class="row">
		{% for a in object_list %}
			<div class="col-11">
				<img class="img-fluid mx-auto d-block mt-3" style="width:310px; height: 310px; border-radius: 75px;image-rendering: -webkit-optimize-contrast;" src="{{ a.pic.url }}"><br><br>
				<h5 class="">در باره ابر جواد : </h5>
				<p class="text-muted mb-4">{{a.description}}</p>
				<h5 class="">مهارت های من</h5>
				<p class="text-muted ">{{a.skils}}</p>
				<p class="text-muted ">{{a.skils1}}</p>
				<p class="text-muted ">{{a.skils2}}</p>
				<p class="text-muted ">{{a.skils3}}</p>
				<p class="text-muted ">{{a.skils4}}</p>
				<p class="text-muted ">{{a.skils5}}</p>
				<p class="text-muted ">{{a.skils6}}</p>
				<p class="text-muted ">{{a.skils7}}</p>
				<p class="text-muted ">{{a.skils8}}</p>
				<p class="text-muted ">{{a.skils9}}</p>
				<p class="text-muted ">{{a.skils10}}</p>
				<p class="text-muted ">{{a.skils11}}</p>
				<p class="text-muted ">{{a.skils12}}</p>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

templates/base.html
<html lang="fa" dir="rtl">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">


<script src="https://use.fontawesome.com/fcf74637dd.js"></script>
<style>
  a{text-decoration: auto;}
</style>
</head>
<body class="bg-light">
  <div class="bg-white shadow sticky-top" style="opacity: 0.95">
  <div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container-fluid">
    <a class="navbar-brand text-primary" href="{% url 'mysite:Article' %}">djavad</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'mysite:Article' %}">خانه</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mysite:ArticleS' %}">مقالات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">اموزشات</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mysite:infos' %}">درباره من</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>
</div>
{% block logo %}

{% endblock %}
{% block header %}

{% endblock %}

{% block content %}
{% endblock %}

{% block up-header %}

{% endblock %}
<div class="bg-dark p-4">
<div class="container">
<div class="row align-items-center">
  <div class="col-md-6">
    <h3 class="text-white">جواد حسین زاده</h3>
    <p class="text-muted mx-3">
      ابر جواد با هدف اشتراک دانش در حوزه تولید نرم افزار های استاندارد در حال خدمت به هموطنان عزیز است
    </p>
    <h3 class="text-white">با ما در تماس باشید</h3>
    <a href="javadhoseinzde80@gmail.com" class="mx-3">javadhoseinzde80@gmail.com</a>
  </div>
</div>
</div>
</div>
</body>
</html>